org: bensayeg
app: fizzbizz-backend
service: fizzbizz-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  profile: ben_development

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:*"
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  users:
    handler: dist/services/users.users_handler
    events:
      - http:
          path: api/v1/user/{username}
          method: get
          request: 
            parameters: 
              paths: 
                username: true      
      - http:
          path: api/v1/user/new
          method: post
      - http:
          path: api/v1/user/{username}
          method: put
          request: 
            parameters: 
              paths: 
                username: true
      - http:
          path: api/v1/user/{username}
          method: delete
          request: 
            parameters: 
              paths: 
                username: true
  bookings:
    handler: dist/services/bookings.bookings_handler
    events:
      - http:
          path: api/v1/booking
          method: get  
      - http:
          path: api/v1/booking/new
          method: post
      - http:
          path: api/v1/booking/{booking_id}
          method: put
          request: 
            parameters: 
              paths: 
                booking_id: true
      - http:
          path: api/v1/booking/{booking_id}
          method: delete
          request: 
            parameters: 
              paths: 
                booking_id: true

plugins:
  - serverless-python-requirements
