# org: bensayeg
# app: fizzbizz-backend
service: fizzbizz-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  # lambdaHashingVersion: '20201221'
  stage: dev
  region: us-east-1
  # profile: ben_development

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  users:
    handler: services/users.users_handler
    events:
      - http:
          path: api/v1/user
          method: get
          cors: true
      - http:
          path: api/v1/user/new
          method: post
          cors: true
      - http:
          path: api/v1/user/{username}
          method: put
          cors: true
          request: 
            parameters: 
              paths: 
                username: true
      - http:
          path: api/v1/user/{username}
          method: delete
          cors: true
          request: 
            parameters: 
              paths: 
                username: true
  bookings:
    handler: services/bookings.bookings_handler
    events:
      - http:
          path: api/v1/booking
          method: get  
          cors: true
      - http:
          path: api/v1/booking/new
          method: post
          cors: true
      - http:
          path: api/v1/booking
          method: put
          cors: true
      - http:
          path: api/v1/booking
          method: delete
          cors: true
